import type {
  ResearchArtifactKind,
  ResearchConnection,
  ResearchNode,
  ResearchNodeStatus,
} from '@/types/research';

export const STATUS_META: Record<
  ResearchNodeStatus,
  { label: string; color: string; background: string }
> = {
  live: { label: '운영 중', color: '#1d6b50', background: '#dff4e8' },
  building: { label: '개발 중', color: '#8a4d08', background: '#fff0d5' },
  review: { label: '검토 필요', color: '#8a3441', background: '#fbe4e8' },
  planned: { label: '예정', color: '#52606d', background: '#e8edf1' },
};

export const ARTIFACT_META: Record<
  ResearchArtifactKind,
  { label: string; icon: string; color: string }
> = {
  product: { label: '기획', icon: 'solar:clipboard-text-outline', color: '#7b61a8' },
  design: { label: '디자인', icon: 'solar:pallete-2-outline', color: '#c45c7a' },
  frontend: { label: '프론트엔드', icon: 'solar:monitor-code-outline', color: '#126b7f' },
  backend: { label: '백엔드', icon: 'solar:server-square-outline', color: '#39704d' },
  qa: { label: 'QA', icon: 'solar:shield-check-outline', color: '#9a6518' },
};

export const RESEARCH_NODES: ResearchNode[] = [
  {
    id: 'landing',
    sequence: '01',
    title: '첫 진입 · 랜딩',
    eyebrow: 'DISCOVER',
    description: '서비스의 약속을 이해하고 첫 체크리스트로 진입하는 시작점',
    route: '/',
    icon: 'solar:home-smile-angle-outline',
    status: 'live',
    progress: 88,
    owner: 'Frontend',
    updatedAt: '07.24',
    tags: ['온보딩', 'SEO', '전환'],
    position: { x: 96, y: 182 },
    artifacts: [
      { id: 'l-p-1', kind: 'product', title: '서비스 비전 · 핵심 사용자', detail: 'PRD Vision / UJ 진입 여정', status: 'ready' },
      { id: 'l-d-1', kind: 'design', title: '랜딩 히어로 · 기능 소개', detail: 'Hero / Testimonial / Feature 섹션', status: 'ready' },
      { id: 'l-f-1', kind: 'frontend', title: 'LandingPage', detail: '랜딩 조합과 로그인 리다이렉트', path: 'src/features/landing/LandingPage.tsx', status: 'ready' },
      { id: 'l-q-1', kind: 'qa', title: '첫 진입 전환 시나리오', detail: '비로그인 → 체크리스트 시작', status: 'working' },
    ],
    decisions: [
      { date: '2026.05', title: 'Vite + React 유지', description: 'Next.js 전환은 ver1.1 범위에서 제외하고 2026년 이후로 미뤘어요.' },
    ],
  },
  {
    id: 'login',
    sequence: '02',
    title: '로그인 · 인증',
    eyebrow: 'DISCOVER',
    description: '게스트 경험을 보존하면서 Kakao/Naver 계정으로 연결',
    route: '/login',
    icon: 'solar:login-3-outline',
    status: 'review',
    progress: 72,
    owner: 'FE + BE',
    updatedAt: '07.22',
    tags: ['OAuth', '게스트', '보안'],
    position: { x: 96, y: 480 },
    artifacts: [
      { id: 'a-p-1', kind: 'product', title: '게스트 한도 정책', detail: '비로그인 2개 · 로그인 5개', status: 'ready' },
      { id: 'a-f-1', kind: 'frontend', title: 'AuthCallbackPage', detail: 'OAuth 콜백과 오류 화면', path: 'src/features/auth/AuthCallbackPage.tsx', status: 'ready' },
      { id: 'a-b-1', kind: 'backend', title: 'PATH C 인증 예외', detail: 'Security filter → AUTH_401', status: 'working' },
      { id: 'a-q-1', kind: 'qa', title: '인증 경계 회귀 테스트', detail: '토큰 만료 · 게스트 데이터 보존', status: 'missing' },
    ],
    decisions: [
      { date: '2026.06', title: 'Security filter 응답 분리', description: '인증 오류는 advice를 우회하는 PATH C로 관리해요.' },
    ],
  },
  {
    id: 'rooms',
    sequence: '03',
    title: '방 목록',
    eyebrow: 'MANAGE',
    description: '살펴본 매물을 한곳에 모으고 다음 행동을 선택',
    route: '/rooms',
    icon: 'solar:buildings-2-outline',
    status: 'building',
    progress: 82,
    owner: 'Frontend',
    updatedAt: '07.28',
    tags: ['목록', '필터', '빈 상태'],
    position: { x: 438, y: 182 },
    artifacts: [
      { id: 'r-p-1', kind: 'product', title: '매물 보관 · 한도 규칙', detail: '게스트/회원별 최대 개수와 빈 상태', status: 'ready' },
      { id: 'r-d-1', kind: 'design', title: '방 카드 · 필터 패턴', detail: '거래방식 / 정렬 / 모바일 통합 필터', status: 'ready' },
      { id: 'r-f-1', kind: 'frontend', title: 'RoomsPage', detail: '목록, 필터, 삭제, 온보딩', path: 'src/features/rooms/pages/RoomsPage.tsx', status: 'ready' },
      { id: 'r-b-1', kind: 'backend', title: 'Room API', detail: '조회 · 수정 · 삭제 IDOR 방어', status: 'working' },
      { id: 'r-q-1', kind: 'qa', title: 'IDOR-ROOM-27 / 31', detail: '타인 방 조회·수정·삭제 차단', status: 'working' },
    ],
    decisions: [
      { date: '2026.07', title: '빈 상태와 필터 결과 분리', description: '첫 사용자 안내와 검색 결과 없음은 다른 행동을 유도해요.' },
    ],
  },
  {
    id: 'checklist',
    sequence: '04',
    title: '현장 체크리스트',
    eyebrow: 'CAPTURE',
    description: '방문 현장에서 놓치기 쉬운 조건을 순서대로 기록',
    route: '/checklist/new',
    icon: 'solar:checklist-minimalistic-outline',
    status: 'building',
    progress: 76,
    owner: 'FE + BE',
    updatedAt: '07.29',
    tags: ['핵심 플로우', '입력', '5개 섹션'],
    position: { x: 780, y: 182 },
    artifacts: [
      { id: 'c-p-1', kind: 'product', title: '5단계 현장 점검 여정', detail: '기본정보 → 건물 → 내부 → 안전 → 메모', status: 'ready' },
      { id: 'c-d-1', kind: 'design', title: '섹션 탭 · 입력 컴포넌트', detail: '모바일 현장 사용성과 상태 피드백', status: 'ready' },
      { id: 'c-f-1', kind: 'frontend', title: 'ChecklistNewPage', detail: '퍼널 상태와 섹션 스크롤', path: 'src/features/checklist/ChecklistNewPage.tsx', status: 'working' },
      { id: 'c-b-1', kind: 'backend', title: 'Checklist API', detail: '예외적으로 /api/checklist prefix 사용', status: 'working' },
      { id: 'c-q-1', kind: 'qa', title: 'API 핸들링 단위 테스트', detail: '400 / 409 / 500 응답 일관성', status: 'working' },
    ],
    decisions: [
      { date: '2026.06', title: '5개 섹션 고정', description: '현장 집중을 위해 긴 단일 폼보다 단계형 기록을 유지해요.' },
    ],
  },
  {
    id: 'custom',
    sequence: '05',
    title: '내 체크항목',
    eyebrow: 'CAPTURE',
    description: '사용자 상황에 맞춰 기본 항목을 켜고 나만의 질문을 추가',
    route: '/custom',
    icon: 'solar:tuning-4-outline',
    status: 'live',
    progress: 91,
    owner: 'Frontend',
    updatedAt: '07.20',
    tags: ['개인화', '설정', '커스텀'],
    position: { x: 780, y: 480 },
    artifacts: [
      { id: 'u-p-1', kind: 'product', title: '사용자 유형별 기본값', detail: '학생 · 직장인 · 반려동물 등', status: 'ready' },
      { id: 'u-d-1', kind: 'design', title: '토글 · 사용자 유형 카드', detail: '선택과 직접 입력 패턴', status: 'ready' },
      { id: 'u-f-1', kind: 'frontend', title: 'SettingsPage', detail: '항목 활성화와 커스텀 저장', path: 'src/features/customization/SettingsPage.tsx', status: 'ready' },
      { id: 'u-b-1', kind: 'backend', title: 'Custom Checklist API', detail: '사용자별 항목 영속화', status: 'ready' },
    ],
    decisions: [],
  },
  {
    id: 'map',
    sequence: '06',
    title: '지도 · 동선',
    eyebrow: 'DECIDE',
    description: '학교와 역 같은 기준점까지 실제 이동 부담을 비교',
    route: '/map',
    icon: 'solar:map-point-wave-outline',
    status: 'review',
    progress: 67,
    owner: 'Frontend',
    updatedAt: '07.27',
    tags: ['지도', '거리', '경로'],
    position: { x: 1122, y: 182 },
    artifacts: [
      { id: 'm-p-1', kind: 'product', title: '기준점 비교 시나리오', detail: '학교 · 역 · 직접 선택 위치', status: 'ready' },
      { id: 'm-d-1', kind: 'design', title: '지도 + 카드 동시 탐색', detail: '선택 상태와 호버 확장', status: 'working' },
      { id: 'm-f-1', kind: 'frontend', title: 'MapPage', detail: '좌표, 기준점, 도보 경로', path: 'src/features/map/MapPage.tsx', status: 'working' },
      { id: 'm-b-1', kind: 'backend', title: 'Geocoding / Juso', detail: '외부 응답 미래핑 시 silent 500', status: 'working' },
      { id: 'm-q-1', kind: 'qa', title: 'silent-500 회귀', detail: '주소 검색 · 지오코딩 응답 매핑', status: 'missing' },
    ],
    decisions: [
      { date: '2026.07', title: '직선거리와 도보시간 구분', description: '사용자가 체감하는 비교를 위해 경로 데이터의 의미를 분리해요.' },
    ],
  },
  {
    id: 'report',
    sequence: '07',
    title: '비교 리포트',
    eyebrow: 'DECIDE',
    description: '2~3개 방의 조건과 위험 신호를 같은 눈금에서 비교',
    route: '/report',
    icon: 'solar:chart-square-outline',
    status: 'building',
    progress: 79,
    owner: 'FE + BE',
    updatedAt: '07.29',
    tags: ['비교', '리포트', '공유'],
    position: { x: 1122, y: 480 },
    artifacts: [
      { id: 'p-p-1', kind: 'product', title: '비교 기준 · 선택 규칙', detail: '2~3개 방 / 최소 1개 섹션', status: 'ready' },
      { id: 'p-d-1', kind: 'design', title: '비교 테이블 · 상태 칩', detail: '위험 · 양호 · 주의 3색 시스템', status: 'ready' },
      { id: 'p-f-1', kind: 'frontend', title: 'ReportPage', detail: '설정 패널, 섹션 탭, 출력', path: 'src/features/report/ReportPage.tsx', status: 'working' },
      { id: 'p-b-1', kind: 'backend', title: 'Report API', detail: '조회 · 수정 IDOR 방어', status: 'working' },
      { id: 'p-q-1', kind: 'qa', title: 'IDOR-RPT-13 / 14', detail: '타인 리포트 조회·수정 차단', status: 'working' },
    ],
    decisions: [
      { date: '2026.07', title: '방 슬롯 색상 고정', description: '스크롤 중에도 같은 방을 빠르게 추적하도록 A/B/C 색을 유지해요.' },
    ],
  },
  {
    id: 'mypage',
    sequence: '08',
    title: '마이페이지',
    eyebrow: 'MANAGE',
    description: '계정 상태와 개인 기록을 관리하는 서비스의 뒤편',
    route: '/my',
    icon: 'solar:user-rounded-outline',
    status: 'planned',
    progress: 38,
    owner: 'Product',
    updatedAt: '07.18',
    tags: ['계정', '기록', '정책'],
    position: { x: 438, y: 480 },
    artifacts: [
      { id: 'y-p-1', kind: 'product', title: '계정 관리 범위', detail: '프로필 · 로그아웃 · 탈퇴 정책', status: 'working' },
      { id: 'y-d-1', kind: 'design', title: '마이페이지 구조', detail: '서비스 설정과 기록 분리', status: 'missing' },
      { id: 'y-f-1', kind: 'frontend', title: 'MyPage', detail: '계정 기본 화면', path: 'src/features/mypage/MyPage.tsx', status: 'working' },
      { id: 'y-q-1', kind: 'qa', title: '계정 경계 테스트', detail: '로그아웃 · 토큰 만료 · 탈퇴', status: 'missing' },
    ],
    decisions: [],
  },
];

export const RESEARCH_CONNECTIONS: ResearchConnection[] = [
  { from: 'landing', to: 'rooms' },
  { from: 'landing', to: 'login', variant: 'support' },
  { from: 'login', to: 'rooms', variant: 'support' },
  { from: 'rooms', to: 'checklist' },
  { from: 'rooms', to: 'map', variant: 'support' },
  { from: 'rooms', to: 'report' },
  { from: 'checklist', to: 'custom', variant: 'support' },
  { from: 'checklist', to: 'map' },
  { from: 'checklist', to: 'report' },
  { from: 'map', to: 'report', variant: 'support' },
  { from: 'rooms', to: 'mypage', variant: 'support' },
];

export const RESEARCH_STATS = {
  pages: RESEARCH_NODES.length,
  resources: RESEARCH_NODES.reduce((sum, node) => sum + node.artifacts.length, 0),
  decisions: RESEARCH_NODES.reduce((sum, node) => sum + node.decisions.length, 0),
  readiness: Math.round(
    RESEARCH_NODES.reduce((sum, node) => sum + node.progress, 0) / RESEARCH_NODES.length,
  ),
};
