CREATE TABLE IF NOT EXISTS rooms (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    address VARCHAR(255) NOT NULL,
    rent_type VARCHAR(20) NOT NULL,
    deposit BIGINT,
    monthly_rent INTEGER,
    maintenance_status VARCHAR(20) NOT NULL,
    maintenance_fee INTEGER,
    has_loan BOOLEAN NOT NULL,
    loan_amount BIGINT,
    can_register_address BOOLEAN NOT NULL,
    available_from DATE,
    building_type VARCHAR(20) NOT NULL,
    floor INTEGER,
    has_elevator BOOLEAN NOT NULL,
    direction VARCHAR(20) NOT NULL,
    memo VARCHAR(1000),
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    deleted_at DATETIME(6),
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);